### ISSUE TITLE
KDF Function

### ISSUE THREAD

**Issue by zanderisrael** [anderson-arlen/cryptoseed#3]
Do you think that adding a KDF function into the mix the overall security against brute forcing will improve?

Do you think there is a way to add more entropy, like adding an email as the salt or somthing like that?

**Comment by anderson-arlen** [comment]
It already uses pbkdf2 and the salt is randomly generated which should be way more secure than user input.

https://github.com/anderson-arlen/cryptoseed/blob/master/src/containers/Application.jsx#L48

**Comment by zanderisrael** [comment]
I see, good!
Im adding cryptoseed to my version bitkey.io (livecd), maybe it will get pulled in.

**Comment by anderson-arlen** [comment]
Sweet. Glad you found it useful. :+1:
