### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mr10008** [anderson-arlen/cryptoseed#5]
Thanks for a great tool!
Most of the time when traveling I don't have my computer with me. So a mobile version would be great to have. Are you planning to create it for Android and maybe for iOS as well?

**Comment by mr10008** [comment]
I tested an Android app to use with your app, 
Crypto - Tools for Encryption, https://play.google.com/store/apps/details?id=com.kokoschka.michael.crypto&showAllReviews=true

You can encrypt/decrypt using AES-256. However when I tried to decrypt the ciphertext created by your CryptoSeed I'm getting this message:
"No valid ciphertext (not base64 encoded)"

Would it be possible that you change the code in the CryptoSeed to Base 64 encoded so that it becomes compatible with the Android Crypto app? That would make it unnecessary to create new app - it's ready for use and it's a very good one. 
Thanks for considering this.

**Comment by anderson-arlen** [comment]
It is base64 encoded, but there are 3 components to it. There is a salt, an initialization vector, and the encrypted data. The 3 components are base64 encoded, then sandwiched together with pipe characters so they can be easily separated again. You're not going to be able to use another application to decrypt it. Instead, you should use your phone to simply decode the QR Code, then transmit that data to your computer for decrypting in CryptoSeed.
